### ISSUE TITLE
'StableDiffusionPipeline' object has no attribute 'clip_skip'

### ISSUE THREAD

**Issue by liang1wang** [rahulunair/stable_diffusion_arc#3]
(sd_arc) xxx@ubuntu:~/sd_arc/stable_diffusion_arc/text_to_image$ python sd_text_to_img.py
Available models are:
1. runwayml/stable-diffusion-v1-5
2. CompVis/stable-diffusion-v1-4
3. stabilityai/stable-diffusion-2-1
4. stabilityai/stable-diffusion-xl-base-1.0
Select a model by entering its number (or press enter to use the default model): 1
Loading the model...
Loading pipeline components...:  71%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 5/7 [00:00<00:00,  9.93it/s]`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  8.16it/s]
Model loaded.
Optimizing the model...
Traceback (most recent call last):
  File "/home/intel/sd_arc/stable_diffusion_arc/text_to_image/sd_text_to_img.py", line 216, in <module>
    model = Text2ImgModel(model_id, device="xpu")
  File "/home/intel/sd_arc/stable_diffusion_arc/text_to_image/sd_text_to_img.py", line 59, in __init__
    self.optimize_pipeline()
  File "/home/intel/sd_arc/stable_diffusion_arc/text_to_image/sd_text_to_img.py", line 142, in optimize_pipeline
    self.pipeline = self._optimize_pipeline(self.pipeline)
  File "/home/intel/sd_arc/stable_diffusion_arc/text_to_image/sd_text_to_img.py", line 108, in _optimize_pipeline
    if isinstance(getattr(pipeline, attr), nn.Module):
  File "/home/intel/anaconda3/envs/sd_arc/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 138, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionPipeline' object has no attribute 'clip_skip'

**Comment by rahulunair** [comment]
Please see _optimize_pipeline here: https://github.com/rahulunair/genAI/blob/main/text_to_image.ipynb , basically we need to be careful when calling ipex.optimize in _optimize_pipeline method, so now I check for if the attribute is there , then only pass it to ipex.optimize. Hope this helps, if it doesn't kindly open again.
